# Importing libraries and loading data

In [41]:
import os
import pandas as pd
import  numpy as np
import matplotlib as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.simplefilter("ignore")

In [42]:
#Read files:
train = pd.read_csv("Train.csv")
test = pd.read_csv("Test.csv")
sub= pd.read_csv("SampleSubmission.csv")

### combine both train and test data sets into one

In [43]:
data=pd.concat([train,test],sort=False).reset_index(drop=True)
data.columns.tolist()

['ID',
 'country',
 'year',
 'urban_or_rural',
 'ghsl_water_surface',
 'ghsl_built_pre_1975',
 'ghsl_built_1975_to_1990',
 'ghsl_built_1990_to_2000',
 'ghsl_built_2000_to_2014',
 'ghsl_not_built_up',
 'ghsl_pop_density',
 'landcover_crops_fraction',
 'landcover_urban_fraction',
 'landcover_water_permanent_10km_fraction',
 'landcover_water_seasonal_10km_fraction',
 'nighttime_lights',
 'dist_to_capital',
 'dist_to_shoreline',
 'Target']

In [44]:
data.head()

ID     country  year urban_or_rural  ghsl_water_surface  \
0  ID_AAIethGy    Ethiopia  2016              R                 0.0   
1  ID_AAYiaCeL    Ethiopia  2005              R                 0.0   
2  ID_AAdurmKj  Mozambique  2009              R                 0.0   
3  ID_AAgNHles      Malawi  2015              R                 0.0   
4  ID_AAishfND      Guinea  2012              U                 0.0   

   ghsl_built_pre_1975  ghsl_built_1975_to_1990  ghsl_built_1990_to_2000  \
0             0.000000                 0.000000                 0.000055   
1             0.000000                 0.000110                 0.000000   
2             0.000000                 0.000000                 0.000000   
3             0.000141                 0.000181                 0.000254   
4             0.011649                 0.017560                 0.017383   

   ghsl_built_2000_to_2014  ghsl_not_built_up  ghsl_pop_density  \
0                 0.000536           0.999408         12.146134   
1                 0.000018           0.999872        113.806716   
2                 0.000000           1.000000          0.000000   
3                 0.000228           0.999195          5.213320   
4                 0.099875           0.853533         31.734661   

   landcover_crops_fraction  landcover_urban_fraction  \
0                 25.489659                  0.879484   
1                 64.136053                  0.601427   
2                  4.400096                  0.131900   
3                 25.379371                  2.017136   
4                  5.081620                 22.815984   

   landcover_water_permanent_10km_fraction  \
0                                 0.000000   
1                                 0.000000   
2                                 0.000000   
3                                11.293841   
4                                 0.005047   

   landcover_water_seasonal_10km_fraction  nighttime_lights  dist_to_capital  \
0                                0.000000          0.000000       278.788451   
1                                0.005427          0.000000       200.986978   
2                                0.003078          0.000000       642.594208   
3                                0.131035          0.000000       365.349451   
4                                0.130475          1.461894       222.867189   

   dist_to_shoreline    Target  
0         769.338378  0.132783  
1         337.135243  0.004898  
2         169.913773  0.097320  
3         613.591610  0.304107  
4         192.926363  0.605328

# EDA

In [45]:
data.shape

(28648, 19)

In [46]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28648 entries, 0 to 28647
Data columns (total 19 columns):
 #   Column                                   Non-Null Count  Dtype  
---  ------                                   --------------  -----  
 0   ID                                       28648 non-null  object 
 1   country                                  28648 non-null  object 
 2   year                                     28648 non-null  int64  
 3   urban_or_rural                           28648 non-null  object 
 4   ghsl_water_surface                       28648 non-null  float64
 5   ghsl_built_pre_1975                      28648 non-null  float64
 6   ghsl_built_1975_to_1990                  28648 non-null  float64
 7   ghsl_built_1990_to_2000                  28648 non-null  float64
 8   ghsl_built_2000_to_2014                  28648 non-null  float64
 9   ghsl_not_built_up                        28648 non-null  float64
 10  ghsl_pop_density                         28648

In [47]:
data.describe().T

count         mean         std  \
year                                     28648.0  2010.271537    4.553145   
ghsl_water_surface                       28648.0     0.027018    0.095199   
ghsl_built_pre_1975                      28648.0     0.041010    0.118721   
ghsl_built_1975_to_1990                  28648.0     0.027820    0.072850   
ghsl_built_1990_to_2000                  28648.0     0.013713    0.034208   
ghsl_built_2000_to_2014                  28648.0     0.018369    0.040241   
ghsl_not_built_up                        28648.0     0.872069    0.242707   
ghsl_pop_density                         28648.0    95.101508  210.079701   
landcover_crops_fraction                 28648.0    21.097237   16.309999   
landcover_urban_fraction                 28648.0    14.079153   23.917510   
landcover_water_permanent_10km_fraction  28648.0     1.668968    7.152657   
landcover_water_seasonal_10km_fraction   28648.0     0.694652    2.383790   
nighttime_lights                         28648.0     9.260498   26.160952   
dist_to_capital                          28648.0   300.584775  269.097712   
dist_to_shoreline                        28648.0   473.801360  355.856845   
Target                                   21454.0     0.350736    0.194376   

                                                 min          25%  \
year                                     1994.000000  2008.000000   
ghsl_water_surface                          0.000000     0.000000   
ghsl_built_pre_1975                         0.000000     0.000000   
ghsl_built_1975_to_1990                     0.000000     0.000000   
ghsl_built_1990_to_2000                     0.000000     0.000037   
ghsl_built_2000_to_2014                     0.000000     0.000109   
ghsl_not_built_up                           0.000859     0.895615   
ghsl_pop_density                            0.000000     2.943082   
landcover_crops_fraction                    0.000000     6.105505   
landcover_urban_fraction                    0.000000     0.705307   
landcover_water_permanent_10km_fraction     0.000000     0.000000   
landcover_water_seasonal_10km_fraction      0.000000     0.001394   
nighttime_lights                            0.000000     0.000000   
dist_to_capital                             0.105306   110.789483   
dist_to_shoreline                           0.112080   158.829182   
Target                                      0.000000     0.195772   

                                                 50%          75%          max  
year                                     2011.000000  2014.000000  2016.000000  
ghsl_water_surface                          0.000000     0.000000     0.991100  
ghsl_built_pre_1975                         0.000160     0.008011     0.894608  
ghsl_built_1975_to_1990                     0.000602     0.010037     0.685010  
ghsl_built_1990_to_2000                     0.000936     0.008823     0.515534  
ghsl_built_2000_to_2014                     0.001727     0.015209     0.649159  
ghsl_not_built_up                           0.992725     0.999592     1.000000  
ghsl_pop_density                           16.424158    64.364772  1902.876955  
landcover_crops_fraction                   19.297194    33.199903    80.064918  
landcover_urban_fraction                    2.599028    13.063126    98.784092  
landcover_water_permanent_10km_fraction     0.000579     0.172243    99.164018  
landcover_water_seasonal_10km_fraction      0.033941     0.375420    56.201637  
nighttime_lights                            0.024074     4.963472   403.455783  
dist_to_capital                           253.537926   403.780077  1908.105037  
dist_to_shoreline                         420.442368   732.552186  1769.523906  
Target                                      0.293574     0.499003     1.000000

In [48]:
data.ghsl_pop_density.unique()

array([ 12.14613395, 113.80671627,   0.        , ...,  46.12746521,
         0.3096956 , 162.18288681])

In [49]:
data.dist_to_capital.unique()

array([ 278.78845059,  200.986978  ,  642.59420757, ...,   33.77544136,
        320.97415338, 1186.13137289])

In [50]:
data.country.unique()

array(['Ethiopia', 'Mozambique', 'Malawi', 'Guinea', 'Cameroon', 'Ghana',
       'Senegal', 'Kenya', 'Tanzania', 'Mali', 'Swaziland', 'Rwanda',
       'Nigeria', 'Lesotho', 'Sierra Leone', 'Central African Republic',
       "Cote d'Ivoire", 'Togo', 'Democratic Republic of Congo', 'Uganda',
       'Burkina Faso', 'Zambia', 'Angola', 'Zimbabwe', 'Benin'],
      dtype=object)

In [51]:
data.ghsl_water_surface.unique()

array([0.        , 0.00057909, 0.18513989, ..., 0.00268349, 0.00033249,
       0.07695039])

In [52]:
data.landcover_crops_fraction.unique()

array([25.48965903, 64.13605339,  4.40009627, ..., 35.67451095,
       18.05078894,  3.91728442])

In [53]:
data.urban_or_rural.unique()

array(['R', 'U'], dtype=object)

In [54]:
data.urban_or_rural.value_counts()

R    18674
U     9974
Name: urban_or_rural, dtype: int64

In [55]:
data.ghsl_built_pre_1975.unique()

array([0.00000000e+00, 1.40510809e-04, 1.16487475e-02, ...,
       5.63401235e-05, 2.68349135e-04, 1.28367246e-01])

In [56]:
data.ghsl_built_1975_to_1990.unique()

array([0.00000000e+00, 1.09829346e-04, 1.81327209e-04, ...,
       8.82661935e-04, 2.79981105e-03, 1.66245067e-05])

In [57]:
data. ghsl_built_1990_to_2000.unique()

array([5.54935857e-05, 0.00000000e+00, 2.54355853e-04, ...,
       3.86147105e-03, 9.32199293e-03, 4.17994893e-02])

In [58]:
data. ghsl_built_2000_to_2014.unique()

array([5.36437995e-04, 1.83048910e-05, 0.00000000e+00, ...,
       4.25270589e-02, 9.97470402e-05, 1.39709599e-01])

In [59]:
data.ghsl_not_built_up.unique()

array([0.99940807, 0.99987187, 1.        , ..., 0.9423993 , 0.99955114,
       0.61317327])

In [60]:
data.landcover_urban_fraction.unique()

array([8.79484345e-01, 6.01427231e-01, 1.31900113e-01, ...,
       1.27055612e+01, 3.05140710e-02, 3.65284529e+01])

In [61]:
data.landcover_water_permanent_10km_fraction.unique()

array([0.00000000e+00, 1.12938411e+01, 5.04740603e-03, ...,
       1.12942594e-03, 3.31766741e-02, 4.49944565e+00])

In [62]:
data.landcover_water_seasonal_10km_fraction.unique()

array([0.        , 0.00542664, 0.00307795, ..., 0.72325189, 0.22262878,
       0.6475056 ])

In [63]:
data.nighttime_lights.unique()

array([ 0.        ,  1.46189384, 22.98197021, ...,  4.73497367,
        0.1751227 ,  4.22469873])

In [64]:
data.dist_to_shoreline.unique()

array([ 769.33837804,  337.13524335,  169.91377329, ...,  781.83377668,
        605.92020425, 1456.10105823])

In [65]:
data.Target.unique()

array([0.13278266, 0.00489837, 0.09731954, ..., 0.23783108, 0.16507109,
              nan])

In [66]:
data.Target.value_counts()

0.000000    1
0.690350    1
0.356732    1
0.403303    1
0.244123    1
           ..
0.286381    1
0.660463    1
0.543110    1
0.193999    1
0.579648    1
Name: Target, Length: 21454, dtype: int64

In [67]:
data.isnull().sum()

ID                                            0
country                                       0
year                                          0
urban_or_rural                                0
ghsl_water_surface                            0
ghsl_built_pre_1975                           0
ghsl_built_1975_to_1990                       0
ghsl_built_1990_to_2000                       0
ghsl_built_2000_to_2014                       0
ghsl_not_built_up                             0
ghsl_pop_density                              0
landcover_crops_fraction                      0
landcover_urban_fraction                      0
landcover_water_permanent_10km_fraction       0
landcover_water_seasonal_10km_fraction        0
nighttime_lights                              0
dist_to_capital                               0
dist_to_shoreline                             0
Target                                     7194
dtype: int64

In [68]:
## cotegorical variable conversion
#import preprocessing module 
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['urban_or_rural'] = le.fit_transform(data['urban_or_rural'])
data['country'] = le.fit_transform(data['country'])

In [69]:
## convert float dtypes to int
data["year"] = data['year'].astype('float')
data["urban_or_rural"] = data['urban_or_rural'].astype('float')
data["country"] = data['country'].astype('float')

In [70]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28648 entries, 0 to 28647
Data columns (total 19 columns):
 #   Column                                   Non-Null Count  Dtype  
---  ------                                   --------------  -----  
 0   ID                                       28648 non-null  object 
 1   country                                  28648 non-null  float64
 2   year                                     28648 non-null  float64
 3   urban_or_rural                           28648 non-null  float64
 4   ghsl_water_surface                       28648 non-null  float64
 5   ghsl_built_pre_1975                      28648 non-null  float64
 6   ghsl_built_1975_to_1990                  28648 non-null  float64
 7   ghsl_built_1990_to_2000                  28648 non-null  float64
 8   ghsl_built_2000_to_2014                  28648 non-null  float64
 9   ghsl_not_built_up                        28648 non-null  float64
 10  ghsl_pop_density                         28648

In [71]:
## separating data into train and test

train=data[data.Target.notnull()].reset_index(drop=True)
test=data[data.Target.isna()].reset_index(drop=True)

In [72]:
train.shape , test.shape

((21454, 19), (7194, 19))

### FEATURE SELECTION

In [73]:
feat_cols = train.drop(["ID","Target"],1)
cols = feat_cols.columns
target=train["Target"]

In [74]:
train[cols].shape , target.shape

((21454, 17), (21454,))

### MODELLING

In [75]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold, cross_val_score,
from sklearn.metrics import log_loss, accuracy_score

In [76]:
# create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(train[cols],target, test_size=0.20, random_state = 2021)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

(17163, 17) (17163,)
(4291, 17) (4291,)


#### EXTREME GRADIENT BOOST

In [77]:
from xgboost import XGBRegressor

In [87]:
#instatiate the model
xgb=XGBRegressor(objective ='reg:linear', n_estimators= 100, colsample_bynode = 0.8, learning_rate = 0.02,max_depth =  7)
xgb.fit(X_train, y_train)
y_pred = xgb.predict(X_test)

#Evaluation
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_pred)
print('Using scikit-lean, the error is {}'.format(mae))

[12:44:49] WARNING: ../src/objective/regression_obj.cu:171: reg:linear is now deprecated in favor of reg:squarederror.
Using scikit-lean, the error is 0.07774138612532006


In [88]:
#Prediction
pred = test[cols]
predictions_xgb  = xgb.predict(pred)

In [91]:
#Formating submission
sub = pd.DataFrame({'ID': test.ID, 'Target': predictions_xgb}) # Creating a submission file
filename = 'x2_sub.csv'

sub.to_csv(filename,index=False)

print('Saved file: ' + filename)

Saved file: x2_sub.csv


In [92]:
sub

ID    Target
0     ID_AAcismbB  0.150817
1     ID_AAeBMsji  0.229445
2     ID_AAjFMjzy  0.629641
3     ID_AAmMOEEC  0.404312
4     ID_ABguzDxp  0.289857
...           ...       ...
7189  ID_zxzKJCMI  0.235030
7190  ID_zyBrpgRp  0.345419
7191  ID_zyMafcYq  0.453954
7192  ID_zyfMsHMG  0.253141
7193  ID_zytUOqJv  0.421662

[7194 rows x 2 columns]

In [101]:
data.duplicated().any()

False